<a href="https://colab.research.google.com/github/jjomathew98/datasci_1_loading/blob/main/HHA507class1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd

#CSV Datasets

In [10]:
path = '/content/drive/MyDrive/Electric_Vehicle_Population_Data csvfile1.csv'
data=pd.read_csv(path)
data.head(10)

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5UXTA6C03P,King,Seattle,WA,98177.0,2023,BMW,X5,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,30,0,36.0,218985539,POINT (-122.38242499999996 47.77279000000004),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1FMCU0EZXN,Yakima,Moxee,WA,98936.0,2022,FORD,ESCAPE,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,38,0,15.0,197264322,POINT (-120.37951169999997 46.55609000000004),PACIFICORP,5.307700e+10
2,1G1FW6S03J,King,Seattle,WA,98117.0,2018,CHEVROLET,BOLT EV,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,36.0,168549727,POINT (-122.37275999999997 47.689685000000054),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
3,5YJSA1AC0D,King,Newcastle,WA,98059.0,2013,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,208,69900,41.0,244891062,POINT (-122.15733999999998 47.487175000000036),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10
4,1FADP5CU8F,Kitsap,Bremerton,WA,98312.0,2015,FORD,C-MAX,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,19,0,26.0,134915000,POINT (-122.65223 47.57192),PUGET SOUND ENERGY INC,5.303508e+10
5,WB523CF03P,Yakima,Selah,WA,98942.0,2023,BMW,IX,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0,0,15.0,236290862,POINT (-120.54187999999999 46.654175000000066),PACIFICORP,5.307700e+10
6,YV4BR0CK2K,King,Bellevue,WA,98004.0,2019,VOLVO,XC90,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,17,0,48.0,125426248,POINT (-122.201905 47.61385),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
7,5YJ3E1EA5K,Thurston,Olympia,WA,98506.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,22.0,477699071,POINT (-122.88747809999995 47.051957300000026),PUGET SOUND ENERGY INC,5.306701e+10
8,5YJ3E1EB6K,Yakima,Yakima,WA,98902.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,14.0,232637037,POINT (-120.52401199999997 46.59739390000004),PACIFICORP,5.307700e+10
9,1N4AZ0CP9G,King,Redmond,WA,98052.0,2016,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,84,0,45.0,178151032,POINT (-122.12302 47.67668),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [11]:
path = '/content/drive/MyDrive/U.S._Chronic_Disease_Indicators__CDI_csv3.csv'
data=pd.read_csv(path)
data.head(10)

<ipython-input-11-c8fb79401c57>:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv(path)

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2010,2010,OR,Oregon,NVSS,Cardiovascular Disease,Mortality from heart failure,NaN,NaN,Number,...,41,CVD,CVD1_4,NMBR,RACE,AIAN,NaN,NaN,NaN,NaN
1,2019,2019,AZ,Arizona,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,4,ALC,ALC1_1,CRDPREV,GENDER,GENF,NaN,NaN,NaN,NaN
2,2019,2019,OH,Ohio,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,39,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
3,2019,2019,US,United States,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,59,ALC,ALC1_1,CRDPREV,RACE,ASN,NaN,NaN,NaN,NaN
4,2015,2015,VI,Virgin Islands,YRBSS,Alcohol,Alcohol use among youth,NaN,%,Crude Prevalence,...,78,ALC,ALC1_1,CRDPREV,GENDER,GENM,NaN,NaN,NaN,NaN
5,2020,2020,AL,Alabama,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,1,ALC,ALC1_2,CRDPREV,RACE,WHT,NaN,NaN,NaN,NaN
6,2015,2015,DE,Delaware,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,10,ALC,ALC1_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
7,2019,2019,FL,Florida,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,12,ALC,ALC1_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
8,2018,2018,KS,Kansas,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,20,ALC,ALC1_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN
9,2013,2013,MS,Mississippi,PRAMS,Alcohol,Alcohol use before pregnancy,NaN,%,Crude Prevalence,...,28,ALC,ALC1_2,CRDPREV,OVERALL,OVR,NaN,NaN,NaN,NaN

In [ ]:
from IPython.core.display import Markdown
Markdown

In [12]:
path = '/content/drive/MyDrive/Crime_Data_from_2020_to_Presentcsv2.csv'
data=pd.read_csv(path)
data.head(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
5,200100501,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,163,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,998.0,NaN,NaN,700 S BROADWAY,NaN,34.0452,-118.2534
6,200100502,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,1315,1,Central,161,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,IC,Invest Cont,442.0,998.0,NaN,NaN,700 S FIGUEROA ST,NaN,34.0483,-118.2631
7,200100504,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,40,1,Central,155,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,998.0,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
8,200100507,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,200,1,Central,101,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,998.0,NaN,NaN,700 BERNARD ST,NaN,34.0677,-118.2398
9,201710201,06/19/2020 12:00:00 AM,05/26/2020 12:00:00 AM,1925,17,Devonshire,1708,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AO,Adult Other,341.0,NaN,NaN,NaN,11900 BALBOA BL,NaN,34.2864,-118.5021

#JSON datasets

In [17]:
import pandas as pd
df_json = pd.read_json("https://data.cms.gov/data-api/v1/dataset/75e8dcb2-78eb-4a7d-a377-9108441966db/data")
data.head(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
5,200100501,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,163,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,998.0,NaN,NaN,700 S BROADWAY,NaN,34.0452,-118.2534
6,200100502,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,1315,1,Central,161,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,IC,Invest Cont,442.0,998.0,NaN,NaN,700 S FIGUEROA ST,NaN,34.0483,-118.2631
7,200100504,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,40,1,Central,155,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,998.0,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
8,200100507,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,200,1,Central,101,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,998.0,NaN,NaN,700 BERNARD ST,NaN,34.0677,-118.2398
9,201710201,06/19/2020 12:00:00 AM,05/26/2020 12:00:00 AM,1925,17,Devonshire,1708,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AO,Adult Other,341.0,NaN,NaN,NaN,11900 BALBOA BL,NaN,34.2864,-118.5021

In [18]:
df_json = pd.read_json('https://data.cms.gov/data-api/v1/dataset/01edb62e-5c45-4f43-8c91-16cba21cbb74/data')
data.head(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
5,200100501,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,163,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,998.0,NaN,NaN,700 S BROADWAY,NaN,34.0452,-118.2534
6,200100502,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,1315,1,Central,161,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,IC,Invest Cont,442.0,998.0,NaN,NaN,700 S FIGUEROA ST,NaN,34.0483,-118.2631
7,200100504,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,40,1,Central,155,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,998.0,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
8,200100507,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,200,1,Central,101,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,998.0,NaN,NaN,700 BERNARD ST,NaN,34.0677,-118.2398
9,201710201,06/19/2020 12:00:00 AM,05/26/2020 12:00:00 AM,1925,17,Devonshire,1708,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AO,Adult Other,341.0,NaN,NaN,NaN,11900 BALBOA BL,NaN,34.2864,-118.5021

In [20]:
df_json = pd.read_json('https://data.cms.gov/data-api/v1/dataset/5f9f1216-6fd9-455d-bfbc-0efade687a4e/data')
data.head(10)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01/08/2020 12:00:00 AM,01/08/2020 12:00:00 AM,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01/01/2020 12:00:00 AM,01/01/2020 12:00:00 AM,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468
5,200100501,01/02/2020 12:00:00 AM,01/01/2020 12:00:00 AM,30,1,Central,163,1,121,"RAPE, FORCIBLE",...,IC,Invest Cont,121.0,998.0,NaN,NaN,700 S BROADWAY,NaN,34.0452,-118.2534
6,200100502,01/02/2020 12:00:00 AM,01/02/2020 12:00:00 AM,1315,1,Central,161,1,442,SHOPLIFTING - PETTY THEFT ($950 & UNDER),...,IC,Invest Cont,442.0,998.0,NaN,NaN,700 S FIGUEROA ST,NaN,34.0483,-118.2631
7,200100504,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,40,1,Central,155,2,946,OTHER MISCELLANEOUS CRIME,...,IC,Invest Cont,946.0,998.0,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
8,200100507,01/04/2020 12:00:00 AM,01/04/2020 12:00:00 AM,200,1,Central,101,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,IC,Invest Cont,341.0,998.0,NaN,NaN,700 BERNARD ST,NaN,34.0677,-118.2398
9,201710201,06/19/2020 12:00:00 AM,05/26/2020 12:00:00 AM,1925,17,Devonshire,1708,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",...,AO,Adult Other,341.0,NaN,NaN,NaN,11900 BALBOA BL,NaN,34.2864,-118.5021

#XLSX Datasets

In [21]:
import pandas as pd

In [36]:
path ="/content/drive/MyDrive/list-of-insp-rpts-lastyear-datasetxlsx3.xlsx"
data=pd.read_excel(path)
data.head(10)

,DOC_TITLE,DOC_DT,SITE_NAME,RPT_URL,ACCESSION_NO
0,Inspection Report - 2023001,3/31/2023,Arkansas Nuclear One,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23129A788
1,Inspection Report - 2023010,2/17/2023,Beaver Valley,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23067A022
2,Inspection Report - 2023001,3/31/2023,Beaver Valley,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23128A148
3,Inspection Report - 2023001,3/31/2023,Braidwood,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23124A225
4,Inspection Report - 2023440,2/17/2023,Browns Ferry,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23082A034
5,Inspection Report - 2023401,2/9/2023,Browns Ferry,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23067A024
6,Inspection Report - 2023091,3/25/2023,Browns Ferry,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23115A000
7,Inspection Report - 2023090,2/13/2023,Browns Ferry,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23048A062
8,Inspection Report - 2023001,3/31/2023,Browns Ferry,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23122A221
9,Inspection Report - 2023001,3/31/2023,Brunswick,"=hyperlink(""http://adamswebsearch2.nrc.gov/idm...",ML23128A351

In [49]:
data = pd.read_excel('/content/drive/MyDrive/DeathProbsE_F_Alt2_TR2014xlsc.xlsx')
data.head(10)

,Probability of death for females by calendar year and by single year of age (ages 0 to 119).,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114,Unnamed: 115,Unnamed: 116,Unnamed: 117,Unnamed: 118,Unnamed: 119,Unnamed: 120
0,Year,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,...,110.000000,111.000000,112.000000,113.000000,114.000000,115.000000,116.000000,117.000000,118.000000,119.000000
1,2011,0.005821,0.000374,0.000244,0.000182,0.000136,0.000122,0.000112,0.000104,0.000097,...,0.554038,0.587280,0.622517,0.659868,0.699460,0.741427,0.781022,0.820073,0.861077,0.904131
2,2012,0.005770,0.000367,0.000239,0.000179,0.000134,0.000120,0.000109,0.000101,0.000094,...,0.547444,0.580291,0.615108,0.652015,0.691135,0.732604,0.774453,0.813175,0.853834,0.896526
3,2013,0.005720,0.000360,0.000235,0.000176,0.000131,0.000117,0.000106,0.000098,0.000091,...,0.543941,0.576578,0.611173,0.647843,0.686714,0.727916,0.768771,0.807210,0.847570,0.889949
4,2014,0.005670,0.000354,0.000231,0.000172,0.000129,0.000115,0.000104,0.000096,0.000089,...,0.540786,0.573233,0.607627,0.644085,0.682730,0.723694,0.763481,0.801655,0.841738,0.883825
5,2015,0.005612,0.000347,0.000226,0.000169,0.000127,0.000112,0.000102,0.000093,0.000086,...,0.537907,0.570181,0.604392,0.640656,0.679095,0.719841,0.758637,0.796569,0.836398,0.878217
6,2016,0.005547,0.000341,0.000223,0.000166,0.000125,0.000110,0.000099,0.000091,0.000084,...,0.535241,0.567356,0.601397,0.637481,0.675730,0.716274,0.754057,0.791760,0.831348,0.872916
7,2017,0.005477,0.000336,0.000219,0.000164,0.000123,0.000108,0.000098,0.000089,0.000082,...,0.532611,0.564568,0.598442,0.634348,0.672409,0.712754,0.749679,0.787163,0.826521,0.867847
8,2018,0.005404,0.000330,0.000215,0.000161,0.000121,0.000107,0.000096,0.000087,0.000081,...,0.530009,0.561809,0.595518,0.631249,0.669124,0.709271,0.745421,0.782693,0.821827,0.862919
9,2019,0.005329,0.000325,0.000212,0.000158,0.000119,0.000105,0.000094,0.000086,0.000079,...,0.527434,0.559080,0.592625,0.628182,0.665873,0.705826,0.741268,0.778331,0.817248,0.858110

In [53]:
data = pd.read_excel('/content/drive/MyDrive/EEO1 2017 PUF.xlsx')
data.head(10)

,Nation,Region,Division,State,CBSA,County,NAICS2,NAICS2_Name,NAICS3,NAICS3_Name,...,AIANM1_2,NHOPIM1_2,TOMRM1_2,WHF1_2,BLKF1_2,HISPF1_2,ASIANF1_2,AIANF1_2,NHOPIF1_2,TOMRF1_2
0,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11338,8680,38649,1502876,191977,169740,139572,7865,7383,32645
1,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",NaN,NaN,...,96,29,75,3733,203,926,201,35,15,48
2,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",111.0,Crop Production,...,*,*,35,*,*,520,*,*,*,21
3,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",112.0,Animal Production and Aquaculture,...,39,*,13,*,115,173,22,13,*,14
4,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",113.0,Forestry and Logging,...,*,*,*,*,*,3,*,*,*,*
5,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",114.0,"Fishing, Hunting and Trapping",...,*,*,*,82,3,8,5,*,*,*
6,United States,NaN,NaN,NaN,NaN,NaN,11.0,"Agriculture, Forestry, Fishing and Hunting",115.0,Support Activities for Agriculture and Forestry,...,*,*,19,660,26,222,23,*,*,11
7,United States,NaN,NaN,NaN,NaN,NaN,21.0,"Mining, Quarrying, and Oil and Gas Extraction",NaN,NaN,...,401,45,308,6112,430,745,459,70,11,103
8,United States,NaN,NaN,NaN,NaN,NaN,21.0,"Mining, Quarrying, and Oil and Gas Extraction",211.0,Oil and Gas Extraction,...,109,*,*,2853,205,327,188,33,*,*
9,United States,NaN,NaN,NaN,NaN,NaN,21.0,"Mining, Quarrying, and Oil and Gas Extraction",212.0,Mining (except Oil and Gas),...,127,*,*,790,22,59,20,17,*,*